# Generated by Django 4.2.11 on 2024-03-06 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=100, verbose_name='Firma nomi')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityModel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('days', models.IntegerField(verbose_name='Davomiyligi ')),
                ('_from', models.DateField(max_length=100, verbose_name='Boshlanish sanasi ')),
                ('_to', models.DateField(max_length=100, verbose_name='Tugash sanasi ')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Lavhalar')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Narxi')),
                ('included_services', models.TextField(verbose_name='Mavjud xizmatlar ')),
                ('contact', models.IntegerField(verbose_name='Telefon raqami ')),
                ('telegram', models.URLField(blank=True, verbose_name='Telegram manzili ')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram manzili ')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=0)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.agencymodel', verbose_name='Firma nomi')),
            ],
        ),
    ]
