# Generated by Django 4.2.11 on 2024-03-07 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitymodel',
            name='month',
            field=models.CharField(choices=[('yanvar', 'yanvar'), ('fevral', 'fevral'), ('mart', 'mart'), ('april', 'april'), ('may', 'may'), ('iyun', 'iyun'), ('iyul', 'iyul'), ('avgust', 'avgust'), ('sentyabr', 'sentyabr'), ('oktyabr', 'oktyabr'), ('noyabr', 'noyabr'), ('dekabr', 'dekabr')], max_length=50, null=True, verbose_name='Oy'),
        ),
        migrations.AlterField(
            model_name='agencymodel',
            name='agency',
            field=models.CharField(max_length=100, null=True, verbose_name='Firma nomi'),
        ),
        migrations.AlterField(
            model_name='facilitymodel',
            name='_from',
            field=models.DateField(max_length=100, null=True, verbose_name='Boshlanish sanasi '),
        ),
        migrations.AlterField(
            model_name='facilitymodel',
            name='_to',
            field=models.DateField(max_length=100, null=True, verbose_name='Tugash sanasi '),
        ),
        migrations.AlterField(
            model_name='facilitymodel',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.agencymodel', verbose_name='Firma nomi'),
        ),
        migrations.AlterField(
            model_name='facilitymodel',
            name='contact',
            field=models.IntegerField(null=True, verbose_name='Telefon raqami '),
        ),
        migrations.AlterField(
            model_name='facilitymodel',
            name='count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='facilitymodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='facilitymodel',
            name='days',
            field=models.IntegerField(null=True, verbose_name='Davomiyligi '),
        ),
        migrations.AlterField(
            model_name='facilitymodel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='facilitymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Lavhalar'),
        ),
        migrations.AlterField(
            model_name='facilitymodel',
            name='included_services',
            field=models.TextField(null=True, verbose_name='Mavjud xizmatlar '),
        ),
        migrations.AlterField(
            model_name='facilitymodel',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram manzili '),
        ),
        migrations.AlterField(
            model_name='facilitymodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True, verbose_name='Narxi'),
        ),
        migrations.AlterField(
            model_name='facilitymodel',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram manzili '),
        ),
    ]
